name: Create Branches
description: Create branches for the release and patch
inputs:
  github-token:
    description: 'The GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create branches
      shell: bash
      run: |
        git checkout "$BRANCH_NAME"

        if [[ "$BRANCH_NAME" == "master" ]]; then
          git checkout -b "patch/$PATCH_VERSION"
          ./.github/scripts/update-project-version.sh "patch/$PATCH_VERSION" "$PATCH_VERSION-patch" ${{ inputs.github-token }} ${{ github.repository }}

          git checkout -b "release/$VERSION" "patch/$PATCH_VERSION"

          ./.github/scripts/update-project-version.sh "release/$VERSION" "$VERSION-release" ${{ inputs.github-token }} ${{ github.repository }}
          ./.github/scripts/update-project-version.sh "patch/$PATCH_VERSION" "$NEXT_PATCH_VERSION-snapshot" ${{ inputs.github-token }} ${{ github.repository }}
          ./.github/scripts/update-project-version.sh "$BRANCH_NAME" "$NEXT_MINOR_VERSION-snapshot" ${{ inputs.github-token }} ${{ github.repository }}
        else
          git checkout -b "release/$VERSION"

          ./.github/scripts/update-project-version.sh "release/$VERSION" "$VERSION-release" ${{ inputs.github-token }} ${{ github.repository }}
          ./.github/scripts/update-project-version.sh "$BRANCH_NAME" "$NEXT_PATCH_VERSION-snapshot" ${{ inputs.github-token }} ${{ github.repository }}
        fi

        git tag -f ${{ github.event.release.tag_name }} "release/$VERSION"
        git push --tags -f
